// <auto-generated />
using System;
using DiscordClone.Api.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiscordClone.Api.Migrations
{
    [DbContext(typeof(DiscordCloneContext))]
    partial class DiscordCloneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<int>("AccountsId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("AccountsId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRole");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountImageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("LastLogonDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountImageId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.AccountChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ChatId");

                    b.ToTable("AccountChat");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.AccountImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AccountImages", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.BasePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.HasKey("Id");

                    b.ToTable("BasePermission");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.ToTable("Chats", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId1")
                        .HasColumnType("int");

                    b.Property<int>("AccountId2")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId1");

                    b.HasIndex("AccountId2");

                    b.ToTable("Friends", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GroupChats", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChatAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<Guid>("GroupChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GroupChatId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("GroupChatId")
                        .IsUnique();

                    b.HasIndex("GroupChatId1");

                    b.ToTable("GroupChatAccount");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.Chat, System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime?>("EditedDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Message<Chat, Guid>");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.GroupChat, System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Message<GroupChat, Guid>");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Message<GroupChat, Guid>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.TextChannel, int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EditedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Message<TextChannel, int>");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Message<TextChannel, int>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.Chat, System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachment<Chat, Guid>");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.GroupChat, System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachment<GroupChat, Guid>");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.TextChannel, int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageAttachment<TextChannel, int>");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.PreviousRegisteredEmailLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<byte[]>("EmailHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varbinary(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("PreviousRegisteredEmailLookups", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ProfileImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("varbinary(4000)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProfileImages", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsServerAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleGeneralChannelPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("RoleGeneralChannelPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleGeneralServerPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("RoleGeneralServerPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleMembershipPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMembershipPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleTextChannelPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("PermissionId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("RoleTextChannelPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleVoiceChannelPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("PermissionId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("RoleVoiceChannelPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.SecurityCredentials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varbinary(256)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("SecurityCredentials", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.SecurityQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LookupId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LookupId");

                    b.ToTable("SecurityQuestions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Servers", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ServerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int?>("AccountId1")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ProfileImageId")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<int?>("VoiceChannelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId1");

                    b.HasIndex("ProfileImageId")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.HasIndex("VoiceChannelId");

                    b.ToTable("ServerProfiles", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<bool>("IsAgeRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("TextChannels", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannelSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TextChannelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TextChannelId");

                    b.ToTable("TextChannelSettings", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("PasswordSetDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.VoiceChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 4);

                    b.Property<bool>("IsAgeRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("VoiceChannels", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.VoiceChannelSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VoiceChannelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VoiceChannelId");

                    b.ToTable("VoiceChannelSettings", (string)null);
                });

            modelBuilder.Entity("ServerProfileTextChannel", b =>
                {
                    b.Property<int>("ServerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("TextChannelId")
                        .HasColumnType("int");

                    b.HasKey("ServerProfileId", "TextChannelId");

                    b.HasIndex("TextChannelId");

                    b.ToTable("ServerProfileTextChannel");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ChannelPermission", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.BasePermission");

                    b.ToTable("ChannelPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ServerPermission", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.BasePermission");

                    b.ToTable("ServerPermissions", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ChatMessage", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.Chat, System.Guid>");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChatMessage", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.GroupChat, System.Guid>");

                    b.HasIndex("ChatId");

                    b.HasDiscriminator().HasValue("GroupChatMessage");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannelMessage", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.TextChannel, int>");

                    b.HasIndex("ChatId");

                    b.HasDiscriminator().HasValue("TextChannelMessage");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ChatMessageAttachment", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.Chat, System.Guid>");

                    b.ToTable("ChatMessageAttachments", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChatMessageAttachment", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.GroupChat, System.Guid>");

                    b.ToTable("GroupChatMessageAttachments", (string)null);
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannelMessageAttachment", b =>
                {
                    b.HasBaseType("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.TextChannel, int>");

                    b.ToTable("TextChannelMessageAttachments", (string)null);
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Account", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.AccountImage", "Image")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.Account", "AccountImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.AccountChat", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithMany("Chats")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Chat", "Chat")
                        .WithMany("Accounts")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Friend", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", null)
                        .WithMany("Friends")
                        .HasForeignKey("AccountId");

                    b.HasOne("DiscordClone.Api.Entities.Account", "Account1")
                        .WithMany()
                        .HasForeignKey("AccountId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Account", "Account2")
                        .WithMany()
                        .HasForeignKey("AccountId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account1");

                    b.Navigation("Account2");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChatAccount", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.GroupChat", "GroupChat")
                        .WithOne("Owner")
                        .HasForeignKey("DiscordClone.Api.Entities.GroupChatAccount", "GroupChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.GroupChat", null)
                        .WithMany("Accounts")
                        .HasForeignKey("GroupChatId1");

                    b.Navigation("Account");

                    b.Navigation("GroupChat");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.Chat, System.Guid>", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.GroupChat, System.Guid>", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.TextChannel, int>", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.Chat, System.Guid>", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.Chat, System.Guid>", "Message")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.GroupChat, System.Guid>", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.GroupChat, System.Guid>", "Message")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.TextChannel, int>", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.TextChannel, int>", "Message")
                        .WithMany("MessageAttachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.PreviousRegisteredEmailLookup", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.PreviousRegisteredEmailLookup", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Role", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Server", "Server")
                        .WithMany("Roles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleGeneralChannelPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.BasePermission", "Permission")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.RoleGeneralChannelPermission", "PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Role", "Role")
                        .WithMany("RoleGeneralChannelPermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleGeneralServerPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.BasePermission", "Permission")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.RoleGeneralServerPermission", "PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Role", "Role")
                        .WithMany("RoleGeneralServerPermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleMembershipPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.BasePermission", "Permission")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.RoleMembershipPermission", "PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Role", "Role")
                        .WithMany("RoleMembershipPermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleTextChannelPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.TextChannel", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.BasePermission", "Permission")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.RoleTextChannelPermission", "PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Role", "Role")
                        .WithMany("RoleTextChannelPermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.RoleVoiceChannelPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.VoiceChannel", "Entity")
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.BasePermission", "Permission")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.RoleVoiceChannelPermission", "PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Role", "Role")
                        .WithMany("RoleVoiceChannelPermission")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.SecurityCredentials", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.SecurityCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.SecurityQuestion", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.PreviousRegisteredEmailLookup", "Lookup")
                        .WithMany("Questions")
                        .HasForeignKey("LookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lookup");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Server", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.Server", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ServerProfile", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Account", null)
                        .WithMany("ServerProfiles")
                        .HasForeignKey("AccountId1");

                    b.HasOne("DiscordClone.Api.Entities.ProfileImage", "Image")
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.ServerProfile", "ProfileImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Server", "Server")
                        .WithMany("ServerProfiles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.VoiceChannel", null)
                        .WithMany("ServerProfile")
                        .HasForeignKey("VoiceChannelId");

                    b.Navigation("Account");

                    b.Navigation("Image");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannel", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Server", "Server")
                        .WithMany("TextChannels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannelSetting", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.TextChannel", null)
                        .WithMany("TextChannelSettings")
                        .HasForeignKey("TextChannelId");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.User", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Account", "Account")
                        .WithOne("User")
                        .HasForeignKey("DiscordClone.Api.Entities.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.VoiceChannel", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Server", "Server")
                        .WithMany("VoiceChannels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.VoiceChannelSetting", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.VoiceChannel", null)
                        .WithMany("VoiceChannelSettings")
                        .HasForeignKey("VoiceChannelId");
                });

            modelBuilder.Entity("ServerProfileTextChannel", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.ServerProfile", null)
                        .WithMany()
                        .HasForeignKey("ServerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.TextChannel", null)
                        .WithMany()
                        .HasForeignKey("TextChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ChannelPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.BasePermission", null)
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.ChannelPermission", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ServerPermission", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.BasePermission", null)
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.ServerPermission", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ChatMessage", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.Chat, System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.ChatMessage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChatMessage", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.GroupChat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannelMessage", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.TextChannel", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.ChatMessageAttachment", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.Chat, System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.ChatMessageAttachment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChatMessageAttachment", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.GroupChat, System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.GroupChatMessageAttachment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannelMessageAttachment", b =>
                {
                    b.HasOne("DiscordClone.Api.Entities.MessageAttachment<DiscordClone.Api.Entities.TextChannel, int>", null)
                        .WithOne()
                        .HasForeignKey("DiscordClone.Api.Entities.TextChannelMessageAttachment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Account", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Friends");

                    b.Navigation("ServerProfiles");

                    b.Navigation("User")
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Chat", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.GroupChat", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Messages");

                    b.Navigation("Owner")
                        .IsRequired();
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.Chat, System.Guid>", b =>
                {
                    b.Navigation("MessageAttachments");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.GroupChat, System.Guid>", b =>
                {
                    b.Navigation("MessageAttachments");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Message<DiscordClone.Api.Entities.TextChannel, int>", b =>
                {
                    b.Navigation("MessageAttachments");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.PreviousRegisteredEmailLookup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Role", b =>
                {
                    b.Navigation("RoleGeneralChannelPermission");

                    b.Navigation("RoleGeneralServerPermission");

                    b.Navigation("RoleMembershipPermission");

                    b.Navigation("RoleTextChannelPermission");

                    b.Navigation("RoleVoiceChannelPermission");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.Server", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("ServerProfiles");

                    b.Navigation("TextChannels");

                    b.Navigation("VoiceChannels");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.TextChannel", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("TextChannelSettings");
                });

            modelBuilder.Entity("DiscordClone.Api.Entities.VoiceChannel", b =>
                {
                    b.Navigation("ServerProfile");

                    b.Navigation("VoiceChannelSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
